build:
    # protoc --go_out=. --go-grpc_out=. user/*.proto
	protoc --go_out ./gen/go/user --go-grpc_out ./gen/go/user ./user/*.proto
	protoc --go_out ./gen/go/cart --go-grpc_out ./gen/go/cart ./cart/*.proto
